package com.example.jobportal.enums;

public enum BusinessType {
	INFORMATIONTECHNOLOGY,
	CONSTRUCTION,
	BASICMETALPRODUCTION,
	CHEMICALINDUSTRIES,
	COMMERCE,
	EDUCATION,
	FINANCIALSERVICE, 
	FOOD,
	TOBACCO,
	TOURISM,
	HOTELS,
	MINING,
	MECHANICAL_AND_ELECTRICAL_ENGINEERING,
	MEDIA,
	TEXTTILES,
	TRANSPORT,
	TELECOMMUNICATION_SERVICE,
	DATAENTRY
	
}
